stages:
  - build_docs
  - deploy_docs
  - notification
variables:
  WEBHOOK_URL: "https://discord.com/api/webhooks/1180275747592609912/N_kk8D3GAGV9xeNJsNEHRudwySxCPLvgtR60BO-BZJLF9PaUHfcCP129VY6I3OLYe0nQ"

build_specification:
  stage: build_docs
  image: ctornau/latex
  cache:
    key: $CI_JOB_NAME
  script: cd docs && latexmk -shell-escape -pdf specification.tex
  rules:
  - changes:
    - docs/*
  artifacts:
    paths:
      - docs/specification.pdf
  allow_failure: true

pages:
  image: alpine:latest
  stage: deploy_docs
  dependencies:
    - build_docs
  script: mv docs/specification.pdf public/specification.pdf

  artifacts:
    paths:
      - public


discord_notification:
  stage: notification
  script:
    - wget https://raw.githubusercontent.com/DiscordHooks/gitlab-ci-discord-webhook/master/send.sh
    - chmod +x send.sh
    - ./send.sh $CI_COMMIT_MESSAGE $WEBHOOK_URL
